### ISSUE TITLE
doubletree url not working on deploy-servers

### ISSUE THREAD

**Issue by birkin** [Brown-University-Library/iip-production#101]
The doubletree url works locally in the runserver environment, but not on the dev/production servers.

Example:
-  on the dev-server clicking the tree icon for `agrippa` yields the url: <https://dlibwwwcit.services.brown.edu/wordlist/latinword/doubletree/agrippa/N>
- that's missing the `iip` url-segment; adding that segment makes the url work properly.

This is probably because the runserver environment assumes the root `iip` part of the segment; the deployment-servers do not. The way around that is to use, in code, the syntax `reverse( urls.py desired-url-root)` -- or, in a template, the syntax `<a href="{% url 'desired-url-root' %}">`

---

**Comment by emylonas** [comment]
this has been fixed. closing
