### ISSUE TITLE
images not showing up as expected (3days?)

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-production#105]
Images that have been added to new inscriptions aren't showing up. We know that we cannot display multiple images at the moment, however, there is a strange behavior that may have to do with how images are identified for an inscription. Until recently, we only had single images for a few inscriptions. The image names were the same as the file name/inscription ID. Although we index image captions, we don't index image names in our Solr indexing script. This makes me think that the code assumes not only that there is only 1 image per file, but that its name is the same as the file name, but with a `.jpg` extension. 

We now have inscriptions with multiple images, so there are images named `sepp0018a.jpg` and not just `sepp0018.jpg` This means that the name of the image doesn't always match the name of the file or the inscription ID. For inscriptions for whom there exists at least one image in our image folder that has the same name as the inscription file/ID, the image displays. This occurs even when the vanilla image file name is the second item. (https://library.brown.edu/iip/viewinscr/sepp0020/)

In cases where both image file names differ from the inscription ID/file name, the image fails to show up and the `noimg.png` file is shown instead. https://library.brown.edu/iip/viewinscr/jeru0552/

Examples:
1. inscription that has one image that is the same as the inscription file name/ID, where that is the image that shows up. https://library.brown.edu/iip/viewinscr/arch0002/ (This is expected behavior)
2. We don't have any inscriptions with only one image that has a name different from the IIP ID.
2. inscription with two images both of whose names differ from the inscription file name/ID (no images are displayed in this case) https://library.brown.edu/iip/viewinscr/anna0001/ 
3. inscription with two images  one whose names differ from the inscription file name/ID. The image that has the same name as the inscription ID displays.(https://library.brown.edu/iip/viewinscr/sepp0020/)

Need to:
1. add indexing for file names, and also figure out syntax for multiple image names and image captions
2. change code to use actual file names
3. change code to handle multiple images (there is another issue on this)

**Comment by emylonas** [comment]
XML snippet showing how images are encoded:
```
    <facsimile>
        <surface>
            <desc>Detail. <persName role="Credit">Zev Radovan</persName></desc>
            <graphic url="Jeru0309.jpg"/>
        </surface>
        <surface>
            <desc>Full inscription. <persName role="Credit">Zev Radovan</persName></desc>
            <graphic url="Jeru0309b.jpg"/>
        </surface>
    </facsimile>
```
XPath for image URL:  `/TEI/facsimile/surface/graphic/@url`
Xpath for image caption: /TEI/facsimile/surface/desc

In order to find all images and also to make sure that URLs and captions match, something like this would work:
```
<xsl:template name="images">
     <xsl:for-each select="surface">
    <xsl:element name="field"
        <xsl:attribute name="name">image</xsl:attribute>
          <xsl:value-of select="tei:graphic/@url"/>|<xsl:value-of select="tei:desc"/>
       </xsl:element>
   </xsl:for-each>
</xsl:template>

I made up how to output the actual values, but I see from the iip_to_solr.xsl file that we have some repeating fields that are just the same field name output with different values. The slight wrinkle here is that each image has two values, a URL and a caption. we need to somehow make sure that they remain paired. 

This is a start, can discuss further.

**Comment by atbradley** [comment]
@emylonas, I noticed iip_to_solr.xsl has an `image` template that doesn't seem to be used (it has a "TODO" comment over it). Is that related to this issue somehow? It doesn't mention `surface`, `tei:graphic` or `tei:desc`.

**Comment by emylonas** [comment]
This is a very old section - it assumes that images are held in the sourceDesc, probably before TEI and EpiDoc even had `<facsimile>`. It also assumes that the images had very specific names, also no longer valid. 

It probably needs to be rewritten, sadly.

**Comment by atbradley** [comment]
@emylonas Your sample captions [above](https://github.com/Brown-University-Library/iip-production/issues/105#issuecomment-780191367) contain `<persName role="Credit">` fields. Do we want to store those in a format we can use from inside the webapp, or are we fine with just taking the text value of `//facsimile/surface/desc`?

**Comment by emylonas** [comment]
@atbradley At the moment, we are displaying all the text content in `<desc>` including the text in the`<persName>` , you can see that here: https://library.brown.edu/iip/viewinscr/jeru0309/ . (I know that there is a missing space, that's a data issue.

I think that right now, the best thing to do would be to extract that as a string. In the future, we may try to dress the string up a bit, but I don't think we'll ever need the photographer's name as data on its own. For ex. in the future, we may italicize the credit but not the caption if there is one, or parenthesize the credit. That all would be likely be handled in the initial solr.xsl script. Hope this makes sense.

**Comment by atbradley** [comment]
@emylonas Do you have any idea for how to display multiple images? We could just stack them on top of each other in the left column where we're showing the single image now, but that could move the transcription far down the page (if there are more than two or three images). We could put the second and third+ images at the bottom to avoid this. Or add a bunch of fancy JavaScript with a carousel or something to display them. Do you have any ideas/preferences?

**Comment by atbradley** [comment]
I've updated the documents @emylonas mentioned in this issue (anna0001 and sepp0020 in the dev solr core. They're showing what I expect. Tomorrow or next week I'll work on the HTML templates to try showing the images.

**Comment by emylonas** [comment]
A few options for displaying images: 
1. Line them up as smaller thumbnails at the top of the page and on click float over the page, something like this: https://usepigraphy.brown.edu/projects/usep/inscription/MD.Balt.JHU.L.11/ (example of library to manage expanding the image)
2. Stack them vertically, as you suggest. Currently we have 10 files with 3 images. 
Examples:  jaff0041,jeru0564 
and 4 files with 4 images:
sepp0031, firi0001, bshe0148, Egal0002 (that last one shouldn't work because of the capital letter. Have notified Chris Z. to fix it. )

**Comment by emylonas** [comment]
On looking further there is a sprinkling of 5, 6 and 7+ image inscriptions. The one with the most, 8, is sepp0031.

**Comment by atbradley** [comment]
@emylonas @birkin It's not pretty, but it works: https://dlibwwwcit.services.brown.edu/iip/viewinscr/sepp0031/.

It looks like the Django template expects a field called display_status, that's in Solr, but isn't created by the XSLT. Any idea where that comes from?

**Comment by atbradley** [comment]
Commit 577801bf1aaa04278d7f75132f120b875df00511 adds captions to images (both the thumbnails and under the expanded, full-size image.

**Comment by emylonas** [comment]
This isn't bad. I'll show and see if there is any feedback and how they feel about making improvements. This one is the extreme case, with lots of images.

**Comment by emylonas** [comment]
@atbradley I've found an incorrect behavior in the production server, with respect to images. When images exist, they are showing up properly. However, when a file has no image, there is no check for non-existence, and the highslide link shows up as broken. See: https://library.brown.edu/iip/viewinscr/akld0009/
In the past,the code displayed the "noimg.png" file when an image was not explicitly specified. The image is here: `{% static "/resources/img/noimg.png" %}` and I have issued a pull request that hasn't been addressed yet, in which I fix some of the other noimg references, which were linking to another branch.

**Comment by atbradley** [comment]
@emylonas That should be fixed now on dev: https://dlibwwwcit.services.brown.edu/iip/viewinscr/akld0009/. I'll do a pull request now.

**Comment by emylonas** [comment]
@emylonas checked, ready to deploy to production

**Comment by atbradley** [comment]
These fixes are merged to master and now live on production.
