### ISSUE TITLE
doubletree url not working

### ISSUE THREAD

**Issue by birkin** [Brown-University-Library/iip-production#110]
- issue occurs in branch: `wordlist-merge`
- example url:  (root-url)/wordlist/latinword/doubletree/a/PREP/
- error: 
    - message: `local variable 'curtext' referenced before assignment`
    - traceback: (line 124) `                if curtext != row[LATIN_TEXT + NEWBUFF]: `

**Comment by emylonas** [comment]
fixed. closing
