### ISSUE TITLE
wordlist cleanup

### ISSUE THREAD

**Issue by birkin** [Brown-University-Library/iip-production#114]
Assuming wordlist_merge branch ends up being deployed, I suggest a brief pause & cleanup. (Again, not 'til existing changes are moved to production.) Candidates for the cleanup:
- remove "/app/libs/wordlist/corrected_latin.csv" if not needed.
- remove "/app/libs/wordlist/latin.csv" if not needed.
- should "/app/libs/wordlist/latin_doubletree_data.txt" come from a github call?
- remove "/app/libs/wordlist/latin_doubletree_data_uniqued.txt" if not needed.
- remove "/app/templates/wordlist/x.html" templates that aren't needed.
- remove "/config/urls.py" wordlist entries that aren't needed.

=

**Comment by birkin** [comment]
I want to assign this to @mina-rhee but that name's not showing up in the Assignees list.

**Comment by emylonas** [comment]
done. closing
