### ISSUE TITLE
CSS change not working in dev branch

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-production#135]
Adam just accepted pull request #134 and installed on dev. The changes are not showing up when I check them on the dev branch. 

So: I can see the changed file in github: https://github.com/Brown-University-Library/iip-production/blob/dev/iip_smr_web_app/static/iip_search_app/css/tei_custom_elements.css (The change to look for is on line 122 `content: "((" attr(ref);`)

However, when I view a file that should be using the new CSS, such as https://dlibwwwcit.services.brown.edu/iip/viewinscr/masa0298/ I see `((char))` in the display instead of `((phoen-mem))` or `((phoen-wau))`

When I inspect that bit of the web page, it looks as if the CSS is coming from this file: https://dlibwwwcit.services.brown.edu/django_media/iip_student_dev_media/iip_search_app/css/tei_custom_elements.css and not the file in iip_smr_web_app 

So something is getting confused.  I can't find why the css file is being called from /django_media/iip_student_dev_media instead of the current repository. I've cleared my cache and reloaded the page.

**Comment by emylonas** [comment]
The production version seems to be using the same CSS, https://library.brown.edu/django_media/iip_student_dev_media/iip_search_app/css/tei_custom_elements.css

**Comment by atbradley** [comment]
I've updated the site on dlib. Is this what you're expecting to see? 
![image](https://user-images.githubusercontent.com/71141/128237704-7b1321dc-7e54-4f70-a04d-7da9f8339fd5.png)

**Comment by emylonas** [comment]
Yes!!!  that's it.

**Comment by emylonas** [comment]
this can move to production when you are able to do so.

**Comment by emylonas** [comment]
This looks ok on production, closing.
