### ISSUE TITLE
Item counts on search page are incorrect

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-production#24]
The search page on the new site is doing various incorrect things. 

- Many Location category items display a 0 count of inscriptions. They seem to return correct result counts, however, when selected and searched. 
- Type of Inscription and Physical Type  display non-0 counts on the search page but return a different count.. For example, "boundary marker" says it has 22 results, but returns 30. 
- Language and Religion return a different count than what the search page shows. 
- Material returns everything in the database, because the term doesn't seem to be transmitted. This is the status line for results of a search on an item in the Material category: 
`Your search for display status:approved AND * yielded 3929 results`
-  The full text search, and metadata search seem to work

**Comment by birkin** [comment]
- re the "Material returns everything in the database..." issue, fixed in commit 465be2faa61c1180f55b975beea2254267f390bf.

**Comment by emylonas** [comment]
This was fixed by Yang in spring 2019.
