### ISSUE TITLE
images are being referenced from dev server

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-production#31]
On this page (and perhaps others) https://library.brown.edu/iip_development/about/why_inscription/
the image at the top of the page is being served from
https://dlibwwwcit.services.brown.edu/django_media/iip_student_dev_media/about/img/about1.jpg
and is not visible when outside Brown. It should be in the prod, not dev server. The image is available here:
https://library.brown.edu/django_media/iip_student_dev_media/about/img/about1.jpg 
The URL is pointing to the wrong server however. 

Is it possible to grep for other such image links in the new IIP?

**Comment by emylonas** [comment]
This is still a problem in the production site. 
for example on this page: https://library.brown.edu/iip/about/why_inscription/
the image is stored here: 
https://dlibwwwcit.services.brown.edu/django_media/iip_student_dev_media/about/img/about1.jpg

perhaps grep across the project?

**Comment by emylonas** [comment]
The urls can be changed so server library.brown.edu in the static pages editing interface

**Comment by emylonas** [comment]
These are all referenced from the static pages. Need to go through and check them.

**Comment by atbradley** [comment]
I've checked the pages linked from the top navbar; they're coming from `library.brown.edu`, GitHub, or wikimedia.org.

**Comment by emylonas** [comment]
@atbradley The images that are coming from older servers are not in the navbar I think, for ex. on https://library.brown.edu/iip/about/why_inscription/, the problem is the image on the page. It's being loaded from: https://library.brown.edu/django_media/iip_student_dev_media/about/img/about1.jpg

I just did grep -r for the string `iip_student_dev_media` across the code base, and came up with nothing. I think that's because this is coming from the django cms, and is hard coded into the about page.  Re-assigning to me.

**Comment by emylonas** [comment]
This is all set. The images also are stored here: https://github.com/Brown-University-Library/iip-production/blob/master/iip_smr_web_app/static/about/img/about1.jpg in the same repo as the code that calls them, but it's probably fine to call them from the django-media directory, as long as it's on the production site. Closing
