### ISSUE TITLE
inscription-page css thought

### ISSUE THREAD

**Issue by birkin** [Brown-University-Library/iip-production#37]
- consider moving the main css file for an [inscription page](https://library.brown.edu/iip/viewinscr/ashk0003a/) (`tei_custom_elements.css'`) from being a part of this repo to being a part of a [data-repo](https://github.com/Brown-University-Library/iip-texts), so that a wider group of people can trigger automatic updates.

**Comment by emylonas** [comment]
same as #28 closing.
