### ISSUE TITLE
Current Location display and solr field

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-production#51]
Add a label "Current Location" underneath "Place Found" label. This will be followed by the contents of the solr "provenance" field. Assume only one provenance now.

Elli creates this in solr.

**Comment by emylonas** [comment]
Have added the provenance solr field

**Comment by emylonas** [comment]
Example: https://library.brown.edu/iip/viewinscr/caes0336/ 
In the XML file there are two places where geographical information is provided - where the object was found `<origin>` and other places it has subsequently been moved to `<provenance>`

The Solr transformation creates 2 fields: 1 for the original find spot called _place_ and one for the provenance information called _provenance_. 

The code that creates the display only handles the _place_ field. It puts in the header **Place Found** followed by the contents of the solr _place_ field.  There should be a new header **Current Location** that is then followed by the contents of the solr _provenance_ field.

The reason that the provenance information appears in the right place at the moment is that it has been appended to the field that populates the "Place Found" information. That is lines 287-289 of the iip_to_solr.xsl script.  It can be deleted after the new field is working.

**Comment by birkin** [comment]
- implemented in commit 697dcbcc0174b0bf05359da868dd723690e70b0a

---
