### ISSUE TITLE
New html for photo captions

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-production#52]
Add underneath photo, and use solr field "photo_caption"

Elli makes xsl to generate that field.

**Comment by birkin** [comment]
- implemented with 2d1a3af8b7bc6ca15725f6f7764e8b31e4a29f95 in branch `photo_caption` -- we'll test when solr is updated, tentatively the week of monday, feb 3 or monday, feb 10.
- changing label to pending.

**Comment by emylonas** [comment]
Hi Birkin - I've added the field to the Solr file and have made a minor change to jeru0309 which has an image, so it'll index.

**Comment by emylonas** [comment]
looks good
