### ISSUE TITLE
Idumea doesn't appear in the list of locations on the main search page

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-production#62]
This is probably because it has no geographical information - no Pleiades ID or coordinates. Should check to see what solr facet generates this information. or if it's because of how the main page is generated.

**Comment by emylonas** [comment]
Same issue, more description #25

**Comment by birkin** [comment]
Example url: <https://library.brown.edu/iip/viewinscr/idum0044/>

**Comment by emylonas** [comment]
It was a data issue. closed with 59914c036
