### ISSUE TITLE
Image URLs to change in order to make the old site display properly

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-production#82]
change all files so URL reads `...projects/iip-images/...` instead of `...projects/Inscriptions/images/...`

**Page: https://library.brown.edu/cds/projects/iip/info/about/** 
http://cds.library.brown.edu/projects/Inscriptions/images/sun_floor.jpg
http://cds.library.brown.edu/projects/Inscriptions/images/arches.jpg
http://cds.library.brown.edu/projects/Inscriptions/images/mosaic1.jpg
http://cds.library.brown.edu/projects/Inscriptions/images/mosaic2.jpg

**Page https://library.brown.edu/cds/projects/iip/info/research-and-teaching/**
http://cds.library.brown.edu/projects/Inscriptions/images/carv2.jpg

**Page https://library.brown.edu/cds/projects/iip/info/related-sites/**
http://cds.library.brown.edu/projects/Inscriptions/images/floor_circle.jpg
http://cds.library.brown.edu/projects/Inscriptions/images/mosaic3.jpg

**Page https://library.brown.edu/cds/projects/iip/info/bibliography/**
http://cds.library.brown.edu/projects/Inscriptions/images/israel_quad.png

**Comment by birkin** [comment]
- images urls changed to access a temporary web-accessible directory.
- the required secure-http url does not seem to be causing a problem, given that the old urls were plain-http.
- old-site with images showing is at: <https://library.brown.edu/cds/projects/iip/info/about/>
