### ISSUE TITLE
facets not working properly

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-production#85]
I did a search for "funerary" or "funerary.epitaph" or "funerary.malediction" and have 1670 results. The URL string is: 
`https://library.brown.edu/iip/mapsearch/?q=(type:funerary%20OR%20type:funerary.epitaph%20OR%20type:funerary.malediction)`

On the results page, I tried to select the facet "jewish" and then had NO results. Because the search string was rewritten as
`display status:approved AND type:funerary AND type:funerary.epitaph AND type:funerary.malediction AND religion:jewish`

The search is now looking for the intersecton of all the items, and not the union of the first three and the intersection of the last one. When I change the first two "AND" values in the URL string to "OR" it works as expected. 

The rewrite should append the new value to the search string with AND, but it should preserve what's already there.

**Comment by birkin** [comment]
Fixed in commit cf6fc1d9f590d7839c5214a6977bdf8ff701d3ad.
