### ISSUE TITLE
Finish Location/Provenance Display handling

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-production#89]
This is related to #51 - this created a new solr field called `provenance` and displayed it separately from the original location information. This issue is a request to clean up the display. 

Currently, the full inscription display, for example, https://library.brown.edu/iip/viewinscr/caes0305/ , shows location metadata  like this: 
**Place Found:**   Caesarea, Coastal Plain.
Current Location: Caesarea Museum

**Place Found:**   Caesarea (Coastal Plain)

**Current Location:**   Caesarea Museum

where the first line comes from the Solr field called "place_found" which used to have extra provenance information appended to it because there was no provenance field. That extra text "Current location: Caesaria Museum" has now been removed in the Solr document. That line should remain; its content is being managed in Solr. 

The 2nd line is extraneous, and shouldn't be here at all. It comes from the Solr field "placeMenu" and seems to have been introduced by mistake.

The 3rd line is the new Solr field called "provenance" and appears as it should. 

So: the change requested in this issue is to remove the 2nd line which derives from the "placeMenu" field.

**Comment by birkin** [comment]
Addressed in commit https://github.com/Brown-University-Library/iip-production/commit/8fc020aad1346b1297fe03343087f4f4f9935f5e; awaiting review.

**Comment by birkin** [comment]
got the all-good from @emylonas; moved into [production](https://github.com/Brown-University-Library/iip-production/commit/8fc020aad1346b1297fe03343087f4f4f9935f5e); closing.
