### ISSUE TITLE
define good query for the to_approve items.

### ISSUE THREAD

**Issue by birkin** [Brown-University-Library/iip-production#91]

**Comment by emylonas** [comment]
This is how far I got:

**Comment by emylonas** [comment]
This is how far I got:
`https://library.brown.edu/search/solr_pub/iip/?indent=on&wt=json&q=display_status:%22to_approve%22`
I know what I need to add is something like `fl:"inscription_id"` but that seems to have no effect.
I am trying to generate list of ids that have the display_status "to_approve"

**Comment by birkin** [comment]
- The specific thing you're looking for:
<https://library.brown.edu/search/solr_pub/iip/?indent=on&wt=json&q=display_status:%22to_approve%22&fl=inscription_id,display_status>
(Note that the field list can also be queried via fl=value_a&fl=value_b.)

- To be explicit about the sort order:
<https://library.brown.edu/search/solr_pub/iip/?indent=on&wt=json&q=display_status:%22to_approve%22&fl=inscription_id,display_status&sort=inscription_id%20asc>
(That's `sort=field`, then space, then `asc` or `desc`.)

- Since the resultset defaults to showing 10 (even when 'response: numfound' shows the total number found), you can be sure you're seeing all the results via:
<https://library.brown.edu/search/solr_pub/iip/?indent=on&wt=json&q=display_status:%22to_approve%22&fl=inscription_id,display_status&sort=inscription_id%20asc&start=0&rows=7000>
(That's explicitly setting `start` and `rows`, and of course rows should be some number greater than the total number of entries.)

- As a check, see a count of all the display-statuses:
<https://library.brown.edu/search/solr_pub/iip/?indent=on&wt=json&q=*:*&facet=on&facet.field=display_status&rows=0>
(Without the `rows=0`, you'll see actual detailed output with the facet-counts at the bottom -- which is useful in some cases. Also note that to get all the counts, the actual query must include all the entries -- `q=*:*`)

- To get a listing of all the display-statuses, showing the to_approved first, and sorting within display_status via id -- _and_ show the counts at the bottom...
<https://library.brown.edu/search/solr_pub/iip/?indent=on&wt=json&q=*:*&fl=inscription_id,display_status&start=0&rows=7000&sort=display_status%20desc,inscription_id%20asc&facet=on&facet.field=display_status>

**Comment by birkin** [comment]
closing; if there are furthur related questions, we can reopen this.
