### ISSUE TITLE
landing-page map doesn't display

### ISSUE THREAD

**Issue by birkin** [Brown-University-Library/iip-production#95]
GanttStart: 2020-11-19
GanttDue: 2021-02-01

##GanttDue: 2020-11-21 

- The [search landing-page](https://library.brown.edu/iip/mapsearch/) isn't displaying maps on load.
    - Note: clicking the Satellite View overlay works (as do the other overlays).

- Briefly looking into this, it appears the js calls to mapbox.com, to get the tiles, are failing.

- [This example call](https://api.tiles.mapbox.com/v4/isawnyu.map-knmctlkh/7/76/52.png?access_token=pk.eyJ1IjoiZGs1OCIsImEiOiJjajQ4aHd2MXMwaTE0MndsYzZwaG1sdmszIn0.VFRnx3NR9gUFBKBWNhhdjw) yields the response:

    ```{"message":"Classic styles are no longer supported; see https://blog.mapbox.com/deprecating-studio-classic-styles-d8892ac38cb4 for more information"}```

---

**Comment by emylonas** [comment]
Fixed so that satellite image map tiles display. Original view had different tiles. OK for now

**Comment by emylonas** [comment]
This is good enough. Closing
